#!/usr/bin/env python3
"""Stage 4 — assemble the shippable bundle.

Runs the whole pipeline and writes a self-contained folder:

    design-explorer/
    ├── design-explorer.html    the artifact a reviewer opens
    ├── design-summary.json     the structured extraction
    ├── assets/*.mmd            one diagram definition per view
    └── README.md               what each view is for, and the open checks

    python3 export_bundle.py design-summary.json -o design-explorer/
    python3 export_bundle.py --document design.md -o design-explorer/   # draft only
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path
from typing import Any, Dict

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import read_json, write_json, write_text  # noqa: E402
from parse_design import parse  # noqa: E402
from render_html import MERMAID_URLS, TEMPLATE, attach_document, render  # noqa: E402

README = """# {title} — design explorer

Generated by [tech-design-explorer]. Open `design-explorer.html` in a browser;
everything is in that one file.

## What is here

| File | What it is |
| --- | --- |
| `design-explorer.html` | The interactive explorer: navigation, diagrams, decisions, risks |
| `design-summary.json` | The structured extraction every view is generated from |
| `assets/*` | One diagram source per view — `.mmd` for mermaid, `.svg` for the hand-laid story lanes |

## Views

{views}

## Reading it

- The left rail is the section list; the top bar filters sections by text.
- Shift/⌘ + scroll zooms a diagram, drag pans it, double-click fits it again.
- `Walkthrough` steps through a flow one message at a time.
- `⤢` on a section header hides everything else.
- `t` toggles light/dark, `/` focuses the filter.

## Regenerating

```sh
python3 scripts/build_views.py design-summary.json -o assets/
python3 scripts/render_html.py design-summary.json -o design-explorer.html
```

Edit `design-summary.json` — not the HTML — and re-render.

{checks}
"""


def bundle(summary: Dict[str, Any], out_dir: Path, *, inline_mermaid: str = "",
           fmt: str = "standalone", mermaid_urls=None, lang: str = "auto") -> Dict[str, Any]:
    out_dir.mkdir(parents=True, exist_ok=True)
    result = render(summary, mermaid_urls=mermaid_urls or MERMAID_URLS,
                    inline_mermaid=inline_mermaid, fmt=fmt, template=TEMPLATE, lang=lang)
    write_text(out_dir / "design-explorer.html", result["_html"])
    clean = {k: v for k, v in result["summary"].items() if not k.startswith("_")}
    write_json(out_dir / "design-summary.json", clean)
    for view in result["views"]:
        for d in view["diagrams"]:
            if d.get("mermaid"):
                write_text(out_dir / "assets" / f'{d["id"]}.mmd', d["mermaid"] + "\n")
            elif d.get("svg"):
                write_text(out_dir / "assets" / f'{d["id"]}.svg', d["svg"] + "\n")

    views_md = "\n".join(
        f'- **{v["title"]}** — ' + "; ".join(d["title"] for d in v["diagrams"])
        for v in result["views"]
    )
    checks_md = ""
    if result["checks"]:
        rows = "\n".join(f'- `{c["level"]}` **{c["view"]}** — {c["message"]}' for c in result["checks"])
        checks_md = f"## Open consistency checks\n\n{rows}\n"
    write_text(out_dir / "README.md", README.format(
        title=result["summary"].get("title", "Technical design"),
        views=views_md or "_no views generated_",
        checks=checks_md,
    ))
    return result


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    src = ap.add_mutually_exclusive_group(required=True)
    src.add_argument("summary", nargs="?", help="design-summary.json")
    src.add_argument("--document", help="parse a markdown design doc first (draft quality)")
    ap.add_argument("-o", "--out-dir", default="design-explorer")
    ap.add_argument("--format", choices=["standalone", "artifact"], default="standalone")
    ap.add_argument("--inline-mermaid", default="")
    ap.add_argument("--mermaid-url", action="append", default=[])
    ap.add_argument("--lang", choices=["auto", "en", "zh"], default="auto")
    ap.add_argument("--with-document", default="",
                    help="ship the source design doc inside the page")
    ap.add_argument("--zip", action="store_true", help="also produce <out-dir>.zip")
    args = ap.parse_args()

    if args.document:
        summary = parse(Path(args.document).read_text(encoding="utf-8"), source=args.document)
        print("! built from the raw parser — review design-summary.json before sharing this")
    else:
        summary = read_json(args.summary)

    if args.with_document:
        summary = attach_document(summary, args.with_document)
    out = Path(args.out_dir)
    result = bundle(summary, out, inline_mermaid=args.inline_mermaid, fmt=args.format,
                    mermaid_urls=args.mermaid_url or None, lang=args.lang)
    print(f"bundle written to {out}/")
    print(f"  design-explorer.html  {(out / 'design-explorer.html').stat().st_size // 1024} KB")
    print(f"  assets/               {sum(len(v['diagrams']) for v in result['views'])} diagram files")
    warns = [c for c in result["checks"] if c["level"] == "warn"]
    if warns:
        print(f"  {len(warns)} consistency warning(s) — see README.md")
    if args.zip:
        shutil.make_archive(str(out), "zip", root_dir=out.parent, base_dir=out.name)
        print(f"  {out}.zip")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
