"""Hand-laid SVG views — the ones auto-layout gets wrong.

A user story is a walk *through* the system: who touches it, in what order, and
where it hands off. Auto-layout hides exactly that, so the story view is drawn on
an explicit grid — one lane per participant, one column per step — the way a
swimlane is drawn on a whiteboard. Nothing here is generated by a layout engine,
so the picture is stable across renders and easy to reason about.

The SVG carries its own <style>, scoped to a root class, defining both themes: it
therefore looks right inline in the explorer *and* as an exported file.
"""

from __future__ import annotations

from typing import Any, Dict, List

from _common import esc, norm_key

LANE_W = 176          # left rail holding the participant names
COL_W = 208           # one step
LANE_H = 96           # one participant row
HEAD_H = 38           # column header strip
PAD = 14

KIND_CLASS = {
    "ui": "k-ui", "service": "k-svc", "store": "k-store", "queue": "k-queue",
    "external": "k-ext", "actor": "k-actor",
}
CHANGE_CLASS = {"added": "c-add", "modified": "c-mod", "removed": "c-del", "existing": ""}


def text_width(text: str, size: float) -> float:
    """Rough advance width: CJK is square, latin is about 0.55em."""
    total = 0.0
    for ch in text:
        total += size if ord(ch) > 0x2E80 else size * 0.55
    return total


def fit_lines(text: str, width: float, size: float, max_lines: int = 3) -> List[str]:
    """Greedy wrap that works for latin words and for CJK runs alike."""
    text = " ".join(str(text or "").split())
    if not text:
        return []
    lines: List[str] = []
    line = ""
    tokens: List[str] = []
    buf = ""
    for ch in text:
        if ord(ch) > 0x2E80:            # CJK breaks anywhere
            if buf:
                tokens.append(buf)
                buf = ""
            tokens.append(ch)
        elif ch == " ":
            if buf:
                tokens.append(buf)
                buf = ""
        else:
            buf += ch
    if buf:
        tokens.append(buf)

    for tok in tokens:
        sep = "" if (not line or ord(tok[0]) > 0x2E80 or ord(line[-1]) > 0x2E80) else " "
        candidate = line + sep + tok
        if line and text_width(candidate, size) > width:
            lines.append(line)
            line = tok
            if len(lines) == max_lines:
                break
        else:
            line = candidate
    if line and len(lines) < max_lines:
        lines.append(line)
    if len(lines) == max_lines and (text_width(" ".join(lines), size) < text_width(text, size) - 1):
        last = lines[-1]
        while last and text_width(last + "…", size) > width:
            last = last[:-1]
        lines[-1] = last.rstrip() + "…"
    return lines


def _tspans(lines: List[str], x: float, y: float, size: float, cls: str = "") -> str:
    out = []
    for i, line in enumerate(lines):
        out.append(f'<tspan x="{x:.0f}" y="{y + i * (size + 3):.0f}">{esc(line, 200)}</tspan>')
    klass = f' class="{cls}"' if cls else ""
    return f'<text{klass}>' + "".join(out) + "</text>"


STYLE = """
.tde-swim text { font-family: inherit; fill: #101828; }
.tde-swim .lane-band { fill: #f4f6fa; }
.tde-swim .lane-band.alt { fill: #eceff6; }
.tde-swim .rail { fill: #ffffff; stroke: #e2e6ee; }
.tde-swim .lane-name { font-size: 13px; font-weight: 600; }
.tde-swim .lane-role { font-size: 11px; fill: #6a7686; }
.tde-swim .col-head { font-size: 11px; fill: #6a7686; letter-spacing: .06em; }
.tde-swim .card { fill: #ffffff; stroke: #cdd4e0; stroke-width: 1.2; }
.tde-swim .card-title { font-size: 12.5px; font-weight: 550; }
.tde-swim .card-note { font-size: 11px; fill: #6a7686; }
.tde-swim .link { stroke: #8794aa; stroke-width: 1.6; fill: none; }
.tde-swim .chip { font-size: 10px; font-weight: 700; }
.tde-swim .k-ui .card { fill: #eef3ff; stroke: #5b7cfa; }
.tde-swim .k-svc .card { fill: #eef7f0; stroke: #3f9d6a; }
.tde-swim .k-store .card { fill: #fff4e6; stroke: #d9862b; }
.tde-swim .k-queue .card { fill: #f4ecff; stroke: #8b5cf6; }
.tde-swim .k-actor .card { fill: #fdeef1; stroke: #e05c76; }
.tde-swim .k-ext .card { fill: #f2f3f5; stroke: #98a2b3; }
.tde-swim .c-add .card { stroke-dasharray: none; stroke-width: 2; stroke: #2f9e5f; }
.tde-swim .c-mod .card { stroke-width: 2; stroke: #cf8b13; }
.tde-swim .c-del .card { stroke-width: 2; stroke: #d8464a; opacity: .72; }
.tde-swim .swim-step { transition: opacity .25s, transform .25s; }
.tde-swim .swim-step.msg-dim { opacity: .26; }
.tde-swim .swim-step.msg-hot .card { stroke-width: 2.6; filter: drop-shadow(0 2px 8px rgba(79,102,245,.45)); }
.tde-swim .link.msg-dim { opacity: .2; }
.tde-swim .link.msg-hot { stroke: #4f66f5; stroke-width: 2.4; }
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) .tde-swim text { fill: #e8edf5; }
  :root:not([data-theme="light"]) .tde-swim .lane-band { fill: #171d27; }
  :root:not([data-theme="light"]) .tde-swim .lane-band.alt { fill: #1b222d; }
  :root:not([data-theme="light"]) .tde-swim .rail { fill: #151b24; stroke: #262f3d; }
  :root:not([data-theme="light"]) .tde-swim .lane-role,
  :root:not([data-theme="light"]) .tde-swim .col-head,
  :root:not([data-theme="light"]) .tde-swim .card-note { fill: #8e9bb0; }
  :root:not([data-theme="light"]) .tde-swim .card { fill: #1e2636; stroke: #3a4761; }
  :root:not([data-theme="light"]) .tde-swim .link { stroke: #7c8aa3; }
  :root:not([data-theme="light"]) .tde-swim .k-ui .card { fill: #1c2647; stroke: #8098ff; }
  :root:not([data-theme="light"]) .tde-swim .k-svc .card { fill: #173026; stroke: #54b487; }
  :root:not([data-theme="light"]) .tde-swim .k-store .card { fill: #33240f; stroke: #d99b45; }
  :root:not([data-theme="light"]) .tde-swim .k-queue .card { fill: #281b40; stroke: #a281f5; }
  :root:not([data-theme="light"]) .tde-swim .k-actor .card { fill: #3a1a24; stroke: #e0788c; }
  :root:not([data-theme="light"]) .tde-swim .k-ext .card { fill: #232a35; stroke: #7b8798; }
}
:root[data-theme="dark"] .tde-swim text { fill: #e8edf5; }
:root[data-theme="dark"] .tde-swim .lane-band { fill: #171d27; }
:root[data-theme="dark"] .tde-swim .lane-band.alt { fill: #1b222d; }
:root[data-theme="dark"] .tde-swim .rail { fill: #151b24; stroke: #262f3d; }
:root[data-theme="dark"] .tde-swim .lane-role,
:root[data-theme="dark"] .tde-swim .col-head,
:root[data-theme="dark"] .tde-swim .card-note { fill: #8e9bb0; }
:root[data-theme="dark"] .tde-swim .card { fill: #1e2636; stroke: #3a4761; }
:root[data-theme="dark"] .tde-swim .link { stroke: #7c8aa3; }
:root[data-theme="dark"] .tde-swim .k-ui .card { fill: #1c2647; stroke: #8098ff; }
:root[data-theme="dark"] .tde-swim .k-svc .card { fill: #173026; stroke: #54b487; }
:root[data-theme="dark"] .tde-swim .k-store .card { fill: #33240f; stroke: #d99b45; }
:root[data-theme="dark"] .tde-swim .k-queue .card { fill: #281b40; stroke: #a281f5; }
:root[data-theme="dark"] .tde-swim .k-actor .card { fill: #3a1a24; stroke: #e0788c; }
:root[data-theme="dark"] .tde-swim .k-ext .card { fill: #232a35; stroke: #7b8798; }
"""


def swimlane(steps: List[Dict[str, Any]], *, uid: str, lanes_meta: Dict[str, Dict[str, str]],
             col_label: str = "Step") -> str:
    """One story, drawn as lanes × steps.

    `steps` is a list of {component, action, outcome, kind, change}; every step
    occupies its own column, in its participant's lane.
    """
    lanes: List[str] = []
    for st in steps:
        name = st.get("component") or "—"
        if name not in lanes:
            lanes.append(name)
    cols = len(steps)
    width = LANE_W + max(1, cols) * COL_W + PAD
    height = HEAD_H + len(lanes) * LANE_H + PAD

    parts: List[str] = [
        f'<svg class="tde-swim" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" '
        f'width="{width}" height="{height}" role="img">',
        f"<style>{STYLE}</style>",
        f'<defs><marker id="ar-{uid}" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" '
        f'markerHeight="7" orient="auto-start-reverse">'
        f'<path d="M0,0 L10,5 L0,10 z" fill="#8794aa"/></marker></defs>',
    ]

    # lane bands + the name rail
    for i, lane in enumerate(lanes):
        y = HEAD_H + i * LANE_H
        alt = " alt" if i % 2 else ""
        parts.append(f'<rect class="lane-band{alt}" x="0" y="{y}" width="{width}" '
                     f'height="{LANE_H}" rx="10"/>')
        meta = lanes_meta.get(norm_key(lane), {})
        parts.append(f'<rect class="rail" x="{PAD / 2:.0f}" y="{y + 10}" width="{LANE_W - PAD}" '
                     f'height="{LANE_H - 20}" rx="9"/>')
        name_lines = fit_lines(lane, LANE_W - 40, 13, 2)
        parts.append(_tspans(name_lines, PAD, y + 34, 13, "lane-name"))
        role = meta.get("role") or meta.get("responsibility") or ""
        if role:
            parts.append(_tspans(fit_lines(role, LANE_W - 40, 11, 1), PAD,
                                 y + 34 + len(name_lines) * 16, 11, "lane-role"))

    # column headers
    for i, st in enumerate(steps):
        x = LANE_W + i * COL_W + 12
        label = st.get("phase") or f"{col_label} {i + 1}"
        parts.append(_tspans([label.upper()], x, 24, 11, "col-head"))

    # connectors first so cards sit on top of them
    def cell(i: int):
        lane_i = lanes.index(steps[i].get("component") or "—")
        x = LANE_W + i * COL_W + 12
        y = HEAD_H + lane_i * LANE_H + 18
        return x, y, COL_W - 24, LANE_H - 36

    for i in range(len(steps) - 1):
        x1, y1, w1, h1 = cell(i)
        x2, y2, _, h2 = cell(i + 1)
        sx, sy = x1 + w1, y1 + h1 / 2
        ex, ey = x2, y2 + h2 / 2
        mid = (sx + ex) / 2
        if abs(sy - ey) < 1:
            d = f"M{sx:.0f},{sy:.0f} L{ex - 4:.0f},{ey:.0f}"
        else:
            d = (f"M{sx:.0f},{sy:.0f} L{mid:.0f},{sy:.0f} "
                 f"Q{mid + 8:.0f},{sy:.0f} {mid + 8:.0f},{sy + (8 if ey > sy else -8):.0f} "
                 f"L{mid + 8:.0f},{ey - (8 if ey > sy else -8):.0f} "
                 f"Q{mid + 8:.0f},{ey:.0f} {mid + 16:.0f},{ey:.0f} L{ex - 4:.0f},{ey:.0f}")
        parts.append(f'<path class="link" data-step="{i + 1}" d="{d}" '
                     f'marker-end="url(#ar-{uid})"/>')

    # the step cards
    for i, st in enumerate(steps):
        x, y, w, h = cell(i)
        meta = lanes_meta.get(norm_key(st.get("component") or ""), {})
        klass = " ".join(filter(None, [
            "swim-step",
            KIND_CLASS.get(meta.get("kind", "external"), "k-ext"),
            CHANGE_CLASS.get(st.get("change") or meta.get("change") or "existing", ""),
        ]))
        parts.append(f'<g class="{klass}" data-step="{i}">')
        parts.append(f'<rect class="card" x="{x}" y="{y}" width="{w}" height="{h}" rx="10"/>')
        title = fit_lines(st.get("action") or "", w - 24, 12.5, 2)
        parts.append(_tspans(title, x + 12, y + 26, 12.5, "card-title"))
        note = st.get("outcome") or ""
        if note:
            parts.append(_tspans(fit_lines(note, w - 24, 11, 2), x + 12,
                                 y + 26 + len(title) * 16, 11, "card-note"))
        marker = {"added": "+", "modified": "~", "removed": "−"}.get(st.get("change") or "")
        if marker:
            # bottom-right, clear of the title's own text box
            parts.append(f'<text class="chip" x="{x + w - 12}" y="{y + h - 9}" '
                         f'text-anchor="end">{marker}</text>')
        parts.append("</g>")

    parts.append("</svg>")
    return "".join(parts)
